name: fitme360
description: A new Flutter project for fitness.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.6
  youtube_player_flutter: ^9.1.1
  audioplayers: ^6.4.0

  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  android_alarm_manager_plus: ^4.0.7
  share_plus: ^11.0.0
  carousel_slider: ^5.0.0
  flip_card: ^0.7.0
  encrypt: ^5.0.3
  rate_limiter: ^1.0.0
  crypto: ^3.0.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/health.png"
flutter:
  uses-material-design: true
  assets:
    - assets/image/splash.png
    - assets/content/
    - assets/sounds/
flutter_native_splash:
  color: "#ffffff"
  image: assets/image/splash.png
  android: true
  ios: true
